stages:
  - prepare
  - build

image: node:latest

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
  - corepack enable
  - corepack prepare pnpm@latest --activate
  - pnpm install --frozen-lockfile

eslint:
  stage: prepare
  cache:
    paths:
      - node_modules/
    policy: pull
  script:
    - pnpm lint
  artifacts:
    reports:
      codequality: gl-codequality.json

build:
  stage: build
  cache:
    paths:
      - node_modules/
    policy: pull
  dependencies:
    - eslint
  script:
    - pnpm build
