services:
  watchtower:
    image: containrrr/watchtower
    env_file: ".env"
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/watchtower/config/config.json:/config.json
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.server.address=:7642"
    ports:
      - "7642:7642"
    depends_on:
      - web
      - api
    networks:
      - main
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  web:
    image: ghcr.io/gxjakkap/bmhk-web:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`bangmodhackathon.com`)"
      - "traefik.http.services.web.loadbalancer.server.port=3000"
      - "com.centurylinklabs.watchtower.enable=true"
    env_file: ".env"
    deploy:
      mode: replicated
      replicas: 2
    restart: unless-stopped
    networks:
      - app_network
  api:
    image: ghcr.io/gxjakkap/bmhk-api:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=Host(`api.bangmodhackathon.com`)"
      - "traefik.http.services.server.loadbalancer.server.port=3001"
      - "com.centurylinklabs.watchtower.enable=true"
    env_file: ".env"
    deploy:
      mode: replicated
      replicas: 2
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
