services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PW:-password}
      POSTGRES_DB: ${DATABASE_NAME:-bmhk_2025}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER:-postgres}"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  watchtower:
    image: containrrr/watchtower
    env_file: ".env"
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.server.address=:7642"
    ports:
      - "7642:7642"
    depends_on:
      - web
      - api
      - postgres
    networks:
      - app_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  web:
    image: ghcr.io/beambeambeam/bmhk-2025-web:main
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`bangmodhackathon.com`) || Host(`www.bangmodhackathon.com`) || Host(`2025.bangmodhackathon.com`)"
      - "traefik.http.services.web.loadbalancer.server.port=3000"
      - "com.centurylinklabs.watchtower.enable=true"
    env_file: ".env"
    deploy:
      mode: replicated
      replicas: 2
    restart: unless-stopped
    networks:
      - app_network
  
  api:
    image: ghcr.io/beambeambeam/bmhk-2025-api:main
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=Host(`api.bangmodhackathon.com`)"
      - "traefik.http.services.server.loadbalancer.server.port=3001"
      - "com.centurylinklabs.watchtower.enable=true"
    env_file: ".env"
    deploy:
      mode: replicated
      replicas: 2
    restart: unless-stopped
    networks:
      - app_network
    depends_on:
      postgres:
        condition: service_healthy

  staff:
    image: ghcr.io/beambeambeam/bmhk-2025-kirin:main
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`kirin.bangmodhackathon.com`)"
      - "traefik.http.services.web.loadbalancer.server.port=3000"
      - "com.centurylinklabs.watchtower.enable=true"
    env_file: ".env"
    deploy:
      mode: replicated
      replicas: 2
    restart: unless-stopped
    networks:
      - app_network

volumes:
  postgres_data:
    driver: local

networks:
  app_network:
    driver: bridge
