export const AWARD_ENUM = {
  FIRST_ROUND: "FIRST_ROUND",
  SECOND_ROUND: "SECOND_ROUND",
  HONORABLE_MENTION: "HONORABLE_MENTION",
  FIRST_RUNNER_UP: "FIRST_RUNNER_UP",
  SECOND_RUNNER_UP: "SECOND_RUNNER_UP",
  WINNER: "WINNER",
} as const
