export const AWARD_ENUM = {
  NONE: "NONE",
  REGISTERED: "REGISTERED",
  ROUND_1_PARTICIPANT: "ROUND_1_PARTICIPANT",
  ROUND_2_PARTICIPANT: "ROUND_2_PARTICIPANT",
  HONORABLE_MENTION: "HONORABLE_MENTION",
  THIRD_PLACE: "3RD_PLACE",
  SECOND_PLACE: "2ND_PLACE",
  FIRST_PLACE: "1ST_PLACE",
} as const
